export class Order {
    address: string;
    alerts_count: number;
    batch_id: number;
    canceling_reason: string;
    coupon_name: string;
    created_at: any;
    deleted_at: any;
    deleted_products: any;
    delivery_fees: number;
    delivery_time: any;
    discount: number;
    dispatcher_id: number;
    driver:any;
    driver_id:number;
    driver_name:string;
    erp_name_purchase:string;
    erp_name_sales:string;
    express_delivery:number;
    express_time:any;
    external_products:any;
    hungerstation_code:string;
    hyper_market_id:number;
    hyper_order_price:number;
    id:number;
    is_confirmed_first_order:boolean;
    is_finalized:boolean;
    latitude:string;
    local_id:number;
    location_name:string;
    longitude:string;
    loyalty_program_money_ratio:number;
    loyalty_program_points:number;
    loyalty_program_points_expiration_date:any;
    map_code:string;
    market_type:any;
    market_type_id:number;
    notes:any;
    on_the_way_status_id:number;
    order_cancellation_reasons_id:number;
    order_cancellation_status_id:number;
    order_code:string;
    order_price:string;
    order_status_id:number;
    payment_type:any;
    payment_type_id:number;
    printer_name:string;
    printer_time:any;
    products:any;
    rate:number;
    receipt_images:any;
    received_cash:number;
    received_value:number;
    received_value_payment_id:number;
    replace_products:any;
    return_status:any;
    return_value:number;
    returning_images:any;
    sent_to_erp:any;
    shopper:any;
    shopper_alarm:any;
    shopper_done_at:any;
    shopper_rate:number;
    shopper_review:any;
    shopper_time:any;
    status:any;
    suggested_hyper_distance:any;
    suggested_hyper_duration:any;
    suggested_hyper_id:number;
    supervisor_accepted_at:any;
    supervisor_alarm:any;
    supervisor_confirmed_at:any;
    supervisor_id:any;
    time_slot:any;
    time_slot_date:any;
    time_slot_id:number;
    timeslot_from:any;
    timeslot_to:any;
    total_distance_travelled:any;
    total_price:string;
    total_time_spent_at_task_till_completion:string;
    updated_at:any;
    user:any;
    user_id:number;
    vat_rate:any;
    vat_value:any;
    why_unable_to_return_order:any;
}
