
export class AProduct {
    id: number;
    box_id: number;
    category_id: number;
    category_name:string;
    images:object;
    sub_category_id: number;
    filter_ar: string;
    filter_en: string;
    price: number;
    size: number;
    description_ar: string;
    description_en: string;
    created_at: any;
    updated_at: any;
    active: boolean;
    minimarket: number;
    offer: number;
    nos: number;
    image: string;
    extension: string;
    offer_price: number;
    offer_expiration_date: any;
    box: number;
    item_id: number;
    product_filter_id: number;
    is_available: boolean;
    user_can_collect: number;
    percentage_increase: number;
    percentage_decrease: number;
    offer_start_date: any;
    sorting: any;
    minimarket_price: number;
    vatable: number;
    panda_sku: any;
    mini_market_offer: number;
    mini_market_offer_start_date: any;
    mini_market_offer_expiration_date: any;
    image_en: string;
    extension_en: string;
    increasing_category_id: number;
    deleted_at: any;
    market_type_id: number;
    deactivation_reason: string;
    created_by: any;
    updated_by: any;
    promoted: number;
    name: string;
    description: string;
    favourite: number;
}
